import Head from "next/head";
import Image from "next/image";
import Leftnavbar from "./components/Leftnavbar";
import Header from "./components/Header";
import Content from "./components/Content";

//import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Leftnavbar />
      <Header />
      <Content />
    </div>
  );
}
